Add Pebble custom notice and change updated
PietroPasotti/charm-events pull request #3
Opened 2024-04-09 21:17 UTC by tonyandrewmeyer

Add the new Pebble events (custom notice and change updated) to the diagrams.

A few drive-by "juju" -> "Juju" as well :smile:.

TODO:
* [ ] Finish updating the simulator as well.
* [ ] Once the Juju docs have been updated make sure that the change update link is correct (currently it's a guess).

2024-04-10 07:16 UTC, PietroPasotti requested changes
Hi! Thanks for this one, unfortunately I saw this a few moments after I merged a commit where I added pebble custom notices and merged the two graphs into one.

Also worth noting that the single source of truth **for the text** is the discourse post: https://discourse.charmhub.io/t/charm-lifecycle/5938/16

so if you want to fix any typos do that there directly, otherwise we'll have to keep in sync manually.

We should probably delete everything but the graph(s) and the simulator from this repo to avoid confusion.

2024-04-10 07:16 UTC, PietroPasotti commented on README.md
> +This is the 'normal' way of using `defer()`: an event `event1` comes in but we are not ready to process it; we `defer()` it; when `event2` comes in, the oeprator framework will first flush the queue
```suggestion
This is the 'normal' way of using `defer()`: an event `event1` comes in but we are not ready to process it; we `defer()` it; when `event2` comes in, the operator framework will first flush the queue and fire `event1`, then fire `event2`. The ordering is preserved: `event1` is consumed before `event2` by the charm.
```

2024-04-10 09:50 UTC, tonyandrewmeyer commented
> Hi! Thanks for this one, unfortunately I saw this a few moments after I merged a commit where I added pebble custom notices and merged the two graphs into one.

All good :smile:. Is it worth finishing up updating simulator for the two new Pebble types, or should I just close this?

2024-04-10 10:48 UTC, PietroPasotti commented
the simulator is not being used and I wouldn't bother maintaining it at this stage, unless we want to look more into fuzz testing

2024-04-11 07:08 UTC, tonyandrewmeyer commented
> the simulator is not being used and I wouldn't bother maintaining it at this stage, unless we want to look more into fuzz testing

I would actually, but I don't think I realistically have time for that at the moment.

2024-04-11 07:08 UTC, closed without merging